packages:
  - '.'

allowBuilds:
  '@anthropic-ai/claude-code': false
  '@prisma/engines': true
  better-sqlite3: true
  core-js: false
  esbuild: true
  node-pty: false
  prisma: true
  protobufjs: false
  tldjs: false
  tree-sitter-bash: false

neverBuiltDependencies:
  - node-pty
