// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Detect which schema is being used to pick the right database URL
const schemaArg = process.argv.find((a) => a.includes("schema.mysql.prisma"));
const url = schemaArg ? process.env.MYSQL_URL : process.env.DATABASE_URL;

export default defineConfig({
  schema: schemaArg || "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url,
  },
});
