// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Detect which schema is being used to pick the right database URL
const schemaArg = process.argv.find((a) => a.includes("schema.mysql.prisma"));

// `migrate`/`db push` need a direct (non-pooled) connection — PgBouncer/Neon's
// pooler doesn't support the advisory locks and prepared statements Prisma
// Migrate relies on. `generate` and runtime queries can use the pooled URL.
const isMigrateCommand = process.argv.some((a) => a === "migrate" || a === "push");
const pgUrl = isMigrateCommand
	? process.env.DIRECT_URL || process.env.PG_URL_1 || process.env.DATABASE_URL
	: process.env.PG_URL_1 || process.env.DATABASE_URL;

const url = schemaArg ? process.env.MYSQL_URL : pgUrl;

export default defineConfig({
	schema: schemaArg || "packages/db/prisma/schema.prisma",
	migrations: {
		path: "packages/db/prisma/migrations",
		seed: "bun packages/db/prisma/seed.ts",
	},
	datasource: {
		url,
	},
});
